### ISSUE TITLE
Feature: option to change the keyword to detect highlight

### ISSUE THREAD

**Issue by wcastand** [Arthie/vscode-tailwindcssinjs#4]
Hi, let me explain the title.
recently Luke Jackson released `oceanwind` to get tailwind in template string without build process (get runtime on client instead) which is really nice since it means you can use it as es module.

your plugin would work for his lib if we could change the keyword to detect when we need the plugin to activate by detecting `ow` instead of `tw`.

would you think it's possible to put it as a parameter of the plugin or detect both by default?

[oceanwind](https://github.com/lukejacksonn/oceanwind)

**Comment by Arthie** [comment]
Hello, I don't think its currently possible to do this. The vscode extension is using [tailwindcssinjs-typescript-plugin](https://github.com/Arthie/tailwindcssinjs/tree/master/packages/typescript-plugin). This typescript plugin enables all of the language features. We need a way to [pass user configuration](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#handling-user-configuration) before this plugin is activated. The only way to make this possible is to provide vscode with a custom/workspace `tsconfig.json` but that will make this extension irrelevant.

I recommend just importing `ow` as `tw` in your projects.
```javascript
import tw from 'https://unpkg.com/oceanwind';
```
This should work since I didn't limit the extension to tailwindcssinjs.
